CREATE DATABASE PANADERIA;
CREATE DATABASE ESCUELA;
CREATE DATABASE NEGOCIO;
CREATE DATABASE JUGUETERIA;
CREATE DATABASE TIENDA;
CREATE DATABASE Biblioteca;

--Selecciona,os la base de datos que vamos a utilizar--
USE ESCUELA;

CREATE TABLE Aumno(
NC VARCHAR(10),
Nombre VARCHAR(40),
APaterno VARCHAR(40),
AMaterno VARCHAR(40),
Semestre INT,
Grupo VARCHAR(1),
Direccion VARCHAR(50),
Telefono VARCHAR(15),
PRIMARY KEY (NC)
);

USE Biblioteca;
CREATE TABLE Libros(
NL INT,
Titulo VARCHAR(50),
Edicion VARCHAR(30),
Fecha VARCHAR(30),
PRIMARY KEY(NL)
);
CREATE TABLE Autor(
NA INT,
Nombre VARCHAR(50),
PaisOrigen VARCHAR(30),
Genero VARCHAR(30),
PRIMARY KEY(NA)
);


